import 'package:get/get.dart';

class LocalString extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'en': {
      "home": "Home",
      "shop": "Shop",
      "category": "Category",
      "cart": "Cart",
      "profile": "Profile",
      "search": "Search",
      "categories": "Categories",
      "all_product": "All Products",
      "see_all": "See all",
      "add_to_cart": "Add To Cart",
      "select_color": "Select Color",
      "select_size": "Select Size",
      "wholesale": "Wholesale",
      "detail": "Details",
      "brand": "Brands",
      "notification": "Notifications",
      "order_history": "Order History",
      "wishlist": "Wishlist",
      "change_password": "Change Password",
      "contact_us": "Contact Us",
      "privacy_policy": "Privacy Policy",
      "language": "Language",
      "delete_account": "Delete Account",
      "total_quantity": "Total Quantity",
      "total_amount": "Total Amount",
      "check_out": "Check Out",
      "logout": "Logout",
      "filter": "Filter",
      "price_lowest": "Price Lowest",
      "price_highest": "Price Highest",
      "reset_filter": "Reset Filter",
      "blog": "Blog",
      "my_cart": "Cart",
      "account": "Account",

      "Load Failed!Click retry!": "Load Failed!Click retry!",
      "release to load more": "release to load more",
      "No more Data": "No more Data",
      "No Data Found": "No Data Found",
      "Refresh": "Refresh",
      "   ": "   ",
      "Looks like you are not logged in yet.": "Looks like you are not logged in yet.",
      "Go to login": "Go to login",
      "Load Failed! Click retry!": "Load Failed! Click retry!",
      "Click here image upload": "Click here image upload",
      "Something Went Wrong": "Something Went Wrong",

      "Confirm Payment": "Confirm Payment",
      "Upload Screenshot of Payment Transaction": "Upload Screenshot of Payment Transaction",
      "Note: Please upload the screenshot of your payment transaction to confirm your payment.": "Note: Please upload the screenshot of your payment transaction to confirm your payment.",
      "Order Now": "Order Now",
      "Confirm CheckOut": "Confirm CheckOut",
      "Name": "Name",
      "Phone Number": "Phone Number",
      "Address": "Address",
      "OK": "OK",
      "Sub Total": "Sub Total",
      "Delivery Fees": "Delivery Fees",
      "Grand Total": "Grand Total",
      "Submit": "Submit",
      "Enter Your Name": "Enter Your Name",
      "Enter Your Phone Number": "Enter Your Phone Number",
      "Address...": "Address...",
      "* Cash on delivery service not avaliable in this region .": "* Cash on delivery service not avaliable in this region .",
      "DeliveryName": "DeliveryName",
      "Select Payment Method": "Select Payment Method",
      "KBZ Pay": "KBZ Pay",
      "0987654321": "0987654321",
      "Check Out": "Check Out",
      "Go to Home": "Go to Home",
      "Cash on Delivery": "Cash on Delivery",
      "Pay Now": "Pay Now",
      "Cart": "Cart",
      "Add To Cart Items": "Add To Cart Items",
      "Qty : ": "Qty : ",
      "Product Name": "Product Name",
      "Please Select Your Region": "Please Select Your Region",
      "Please Select Your Township": "Please Select Your Township",
      "Forgot Password": "Forgot Password",
      "Continue": "Continue",
      "Enter your email": "Enter your email",
      "Sign In": "Sign In",
      "Please Sign In to continue": "Please Sign In to continue",
      "Forgot Password ?": "Forgot Password ?",
      "Don't have an account? ": "Don't have an account? ",
      "Sign Up Here": "Sign Up Here",
      "Enter your phone number": "Enter your phone number",
      "Password": "Password",
      "Create Account": "Create Account",
      "Welcome": "Welcome",
      "You can sign up here": "You can sign up here",
      "Agree With": "Agree With",
      "Term & Conditions": "Term & Conditions",
      "Sign Up": "Sign Up",
      "Do you have an account?": "Do you have an account?",
      "  Sign In ": "  Sign In ",
      "Enter your name": "Enter your name",
      "Enter your phone": "Enter your phone",
      "Confirm Password": "Confirm Password",
      "*": "*",
      "Verify OTP": "Verify OTP",
      "Verification": "Verification",
      "We have sent verification code to - ": "We have sent verification code to - ",
      "Didn't receive the code? ": "Didn't receive the code? ",
      "RESEND": "RESEND",
      "Edit Profile": "Edit Profile",
      "Update": "Update",
      "  ": "  ",
      "Order History Detail": "Order History Detail",
      "Refund": "Refund",
      "Order Items": "Order Items",
      "Payment Type": "Payment Type",
      "Testing": "Testing",
      "Size : 40": "Size : 40",
      "Color : ": "Color : ",
      "Qty : 10": "Qty : 10",
      "Wholesale": "Wholesale",
      "Order History": "Order History",
      "No order history": "No order history",
      "Chat": "Chat",
      "load more message": "load more message",
      "Release to load more": "Release to load more",
      "No more message": "No more message",
      "Waiting to record": "Waiting to record",
      "Message ..": "Message ..",
      "Contact Us": "Contact Us",
      "No contact information available.": "No contact information available.",
      "If you need any question, you can call any time": "If you need any question, you can call any time",
      "Change Password": "Change Password",
      "Whitelist": "Whitelist",
      "Update Password": "Update Password",
      "Category : ": "Category : ",
      "Brand : ": "Brand : ",
      "Product Detail": "Product Detail",
      "Add to Cart": "Add to Cart",
      "No Image": "No Image",
      "1": "1",
      "No brands available": "No brands available",

      "Are you sure you want to delete your account?": "Are you sure you want to delete your account?",
      "All of data will loss.": "All of data will loss.",
      "No, Keep it": "No, Keep it",
      "Yes, Delete it": "Yes, Delete it",

      "New Arrivals": "New Arrivals",
      "Comment": "Comment",
      "Popular Products": "Popular Products",
      "Current Points : 100 ": "Current Points : 100 ",
      "No products found": "No products found",
      "Intermediate": "Intermediate",

      "My Cart": "My Cart",
      "Clear   ": "Clear   ",
      "Item(s) in my cart": "Item(s) in my cart",
      "Delete all items": "Delete all items",
      "No Products in Cart ": "No Products in Cart ",
      " + Add Products": " + Add Products",
      "Retry": "Retry",
      "No subcategories found": "No subcategories found",
      "In Stock": "In Stock",
      "Dior": "Dior",
      "ChainSaw": "ChainSaw",
      "Box": "Box",
      "Search Product": "Search Product",


      "No Internet Connection": "No Internet Connection",
      "Please check your network settings and try again.": "Please check your network settings and try again.",
      "Cancel": "Cancel",
      "Please upload your payment screenshoot": "Please upload your payment screenshoot",
      "Done": "Done",
      "Enter Full Address": "Enter Full Address",
      "Remark": "Remark",
      "Please fill Phone and Password": "Please fill Phone and Password",
      "Please fill Name": "Please fill Name",
      "Please fill Phone Number": "Please fill Phone Number",
      "Please fill Password": "Please fill Password",
      "Please fill Confirm Password": "Please fill Confirm Password",
      "Password are not the same": "Password are not the same",
      "Agree , Term & Conditions": "Agree , Term & Conditions",
      "continue": "continue",
      "Did not receive the code": "Did not receive the code",
      "Point History": "Point History",
      "Exchange Products": "Exchange Products",
      "Your Current Points": "Your Current Points",
      "Withdraw Money": "Withdraw Money",
      "Enter Point Amount": "Enter Point Amount",
      "Enter Account Number": "Enter Account Number",
      "Enter Account Name": "Enter Account Name",
      "Point Amount": "Point Amount",
      "Account Number": "Account Number",
      "Account Name": "Account Name",
      "Add To Cart": "Add To Cart",
      "Buy Now": "Buy Now",
      "Exchange": "Exchange",
      "Membership": "Membership",
      "Current Points": "Current Points",
      "Profile": "Profile",
      "Wishlist": "Wishlist",
      "Privacy Policy": "Privacy Policy",
      "Delete Account": "Delete Account",
      "App Setting": "App Setting",
      "Language": "Language",
      "Logout": "Logout",
      "Current Points : ": "Current Points : ",
      "Total Earn Points": "Total Earn Points",
      "Withdraw Successful 🎉": "Withdraw Successful 🎉",
      "Account Settings":"Account Settings"
    },
    // 'mm': {
    //   "home": "ပင်မ",
    //   "shop": "ဈေးဝယ်",
    //   "category": "အမျိုးအစား",
    //   "cart": "ဈေးလှည်း",
    //   "profile": "ပရိုဖိုင်",
    // },
    'mm': {
      "home": "ပင်မစာမျက်နှာ",
      "shop": "စျေးဝယ်ရန်",
      "category": "အမျိုးအစား",
      "cart": "ဈေးခြင်း",
      "profile": "ကိုယ်ရေးအချက်အလက်",
      "search": "ရှာဖွေရန်",
      "categories": "အမျိုးအစားများ",
      "all_product": "ကုန်ပစ္စည်းအားလုံး",
      "see_all": "အားလုံးကြည့်မည်",
      "add_to_cart": "ဈေးခြင်းထဲထည့်မည်",
      "select_color": "အရောင်ရွေးပါ",
      "select_size": "အရွယ်အစားရွေးပါ",
      "wholesale": "လက်ကား",
      "detail": "အသေးစိတ်",
      "brand": "အမှတ်တံဆိပ်များ",
      "notification": "အသိပေးချက်များ",
      "order_history": "အော်ဒါမှတ်တမ်း",
      "wishlist": "စိတ်ဝင်စားသည့်ပစ္စည်းများ",
      "change_password": "လျှို့ဝှက်နံပါတ်ပြောင်းရန်",
      "contact_us": "ဆက်သွယ်ရန်",
      "privacy_policy": "ကိုယ်ရေးအချက်အလက်",
      "language": "ဘာသာစကား",
      "delete_account": "အကောင့်ဖျက်ရန်",
      "total_quantity": "စုစုပေါင်းအရေအတွက်",
      "total_amount": "စုစုပေါင်းငွေပမာဏ",
      "check_out": "ငွေပေးချေခြင်း",
      "logout": "ထွက်",
      "filter": "စစ်ထုတ်ရန်",
      "price_lowest": "ဈေးအနိမ့်ဆုံး",
      "price_highest": "ဈေးအမြင့်ဆုံး",
      "reset_filter": "စစ်ထုတ်မှု ပြန်လည်သတ်မှတ်မည်",
      "blog": "ဘလော့ဂ်",
      "my_cart": "ဈေးခြင်း",
      "account": "အကောင့်",

      "Load Failed!Click retry!": "ဖိုင် မတင်နိုင်ပါ! ထပ်မံကြိုးစားရန်နှိပ်ပါ",
      "release to load more": "ထပ်တင်ရန် လွှတ်ပါ",
      "No more Data": "ဒေတာ မရှိတော့ပါ",
      "No Data Found": "ဒေတာ မတွေ့ပါ",
      "Refresh": "ပြန်လည်အသက်သွင်းမယ်",
      "   ": "   ",
      "Looks like you are not logged in yet.": "သင့်အကောင့်ထဲဝင်ထားခြင်း မရှိသေးပါ",
      "Go to login": "အကောင့်ဝင်ရန် သွားမယ်",
      "Load Failed! Click retry!": "တင်ခြင်း မအောင်မြင်ပါ! ထပ်မံကြိုးစားရန်နှိပ်ပါ",
      "Click here image upload": "ဓာတ်ပုံတင်ရန် ဤနေရာကိုနှိပ်ပါ",
      "Something Went Wrong": "တစ်စုံတစ်ရာ မှားယွင်းသွားပါသည်",

      "Confirm Payment": "ငွေပေးချေမှု အတည်ပြုမယ်",
      "Upload Screenshot of Payment Transaction": "ငွေပေးချေမှု အကြောင်းအရာ စကရင်ရှော့တင်ရန်",
      "Note: Please upload the screenshot of your payment transaction to confirm your payment.": "မှတ်ချက် - သင့်ငွေပေးချေမှုကို အတည်ပြုရန် စကရင်ရှော့တင်ပေးပါ",
      "Order Now": "အခုမှာမယ်",
      "Confirm CheckOut": "ဝယ်ယူမှု အတည်ပြုမယ်",
      "Name": "အမည်",
      "Phone Number": "ဖုန်းနံပါတ်",
      "Address": "လိပ်စာ",
      "OK": "အိုကေ",
      "Sub Total": "စုစုပေါင်း",
      "Delivery Fees": "ပို့ဆောင်ခ",
      "Grand Total": "စုစုပေါင်းကျသင့်ငွေ",
      "Submit": "တင်သွင်းမယ်",
      "Enter Your Name": "သင့်အမည် ထည့်ပါ",
      "Enter Your Phone Number": "သင့်ဖုန်းနံပါတ် ထည့်ပါ",
      "Address...": "လိပ်စာ...",
      "* Cash on delivery service not avaliable in this region .": "* ဤဒေသတွင် အိမ်တင်ငွေချေ ဝန်ဆောင်မှု မရှိပါ",
      "DeliveryName": "ပို့ဆောင်သူအမည်",
      "Select Payment Method": "ငွေပေးချေမှု နည်းလမ်းရွေးပါ",
      "KBZ Pay": "KBZ Pay",
      "0987654321": "0987654321",
      "Check Out": "ထွက်မယ်",
      "Go to Home": "ပင်မစာမျက်နှာ သွားမယ်",
      "Cash on Delivery": "အိမ်တင် ငွေချေ",
      "Pay Now": "အခု ငွေချေမယ်",
      "Cart": "စျေးခြင်းထဲ",
      "Add To Cart Items": "ထည့်ရန်",
      "Qty : ": "အရေအတွက် : ",
      "Product Name": "ကုန်ပစ္စည်းအမည်",
      "Please Select Your Region": "သင့်ဒေသရွေးပါ",
      "Please Select Your Township": "သင့်မြို့နယ်ရွေးပါ",
      "Forgot Password": "လျှို့ဝှက်စကားမေ့နေပါသလား",
      "Continue": "ဆက်လက်လုပ်ဆောင်မယ်",
      "Enter your email": "သင့်အီးမေး ထည့်ပါ",
      "Sign In": "အကောင့်ဝင်မယ်",
      "Please Sign In to continue": "ဆက်လက်လုပ်ဆောင်ရန် အကောင့်ဝင်ပါ",
      "Forgot Password ?": "လျှို့ဝှက်စကားမေ့နေပါသလား ?",
      "Don't have an account? ": "အကောင့်မရှိဘူးလား? ",
      "Sign Up Here": "အကောင့်ဖွင့်ရန် ဤနေရာ",
      "Enter your phone number": "သင့်ဖုန်းနံပါတ် ထည့်ပါ",
      "Password": "လျှို့ဝှက်စကား",
      "Create Account": "အကောင့်ဖွင့်မယ်",
      "Welcome": "ကြိုဆိုပါတယ်",
      "You can sign up here": "ဤနေရာတွင် အကောင့်ဖွင့်နိုင်သည်",
      "Agree With": "သဘောတူသည်",
      "Term & Conditions": "စည်းကမ်းချက်များ",
      "Sign Up": "အကောင့်ဖွင့်မယ်",
      "Do you have an account?": "အကောင့်ရှိပြီးသားလား?",
      "  Sign In ": "  အကောင့်ဝင်မယ် ",
      "Enter your name": "အမည်ထည့်ပါ",
      "Enter your phone": "ဖုန်းနံပါတ်ထည့်ပါ",
      "Confirm Password": "လျှို့ဝှက်စကား အတည်ပြုပါ",
      "*": "*",
      "Verify OTP": "OTP အတည်ပြုပါ",
      "Verification": "အတည်ပြုခြင်း",
      "We have sent verification code to - ": "အတည်ပြုကုဒ် ကို ပို့ပေးထားပါသည် - ",
      "Didn't receive the code? ": "ကုဒ် မရဘူးလား? ",
      "RESEND": "ထပ်ပို့မယ်",
      "Edit Profile": "ကိုယ်ရေးအကျဉ်း ပြင်မယ်",
      "Update": "နောက်ဆုံးပေါင်း",
      "  ": "  ",
      "Order History Detail": "အော်ဒါ မှတ်တမ်းအသေးစိတ်",
      "Refund": "ပြန်ပေးငွေ",
      "Order Items": "အော်ဒါထားသောပစ္စည်းများ",
      "Payment Type": "ငွေပေးချေမှုနည်းလမ်း",
      "Testing": "စမ်းသပ်ခြင်း",
      "Size : 40": "အရွယ် : 40",
      "Color : ": "အရောင် : ",
      "Qty : 10": "အရေအတွက် : 10",
      "Wholesale": "လက်ကား",
      "Order History": "အော်ဒါမှတ်တမ်း",
      "No order history": "အော်ဒါမှတ်တမ်း မရှိပါ",
      "Chat": "စာပို့မယ်",
      "load more message": "စာပို့မှုများ ထပ်တင်ရန်",
      "Release to load more": "ထပ်တင်ရန် လွှတ်ပါ",
      "No more message": "မက်ဆေ့ချ် မရှိတော့ပါ",
      "Waiting to record": "အသံဖမ်းရန် စောင့်နေသည်",
      "Message ..": "မက်ဆေ့ချ် ..",
      "Contact Us": "ဆက်သွယ်ရန်",
      "No contact information available.": "ဆက်သွယ်ရန် အချက်အလက် မရှိပါ",
      "If you need any question, you can call any time": "မေးမြန်းလိုပါက အချိန်မရွေး ဖုန်းခေါ်နိုင်သည်",
      "Change Password": "လျှို့ဝှက်စကား ပြောင်းမယ်",
      "Whitelist": "အခွင့်ပြုစာရင်း",
      "Update Password": "လျှို့ဝှက်စကား ပြင်ဆင်မယ်",
      "Category : ": "အမျိုးအစား : ",
      "Brand : ": "ကုမ္ပဏီ : ",
      "Product Detail": "ကုန်ပစ္စည်းအသေးစိတ်",
      "Add to Cart": "စျေးခြင်းထဲထည့်မယ်",
      "No Image": "ဓာတ်ပုံ မရှိပါ",
      "1": "၁",
      "No brands available": "ကုမ္ပဏီ မရှိပါ",

      "Are you sure you want to delete your account?": "သင့်အကောင့် ဖျက်ချင်သလား?",
      "All of data will loss.": "သင့်ဒေတာ အားလုံး ပျက်ဆုံးသွားမည်",
      "No, Keep it": "မဖျက်ပါ၊ ထိန်းထားမယ်",
      "Yes, Delete it": "ဖျက်မယ်",

      "New Arrivals": "အသစ်ရောက်ပစ္စည်းများ",
      "Comment": "အမြင်",
      "Popular Products": "အများနှစ်သက်သောပစ္စည်းများ",
      "Current Points : 100 ": "လက်ရှိ မှတ်ပုံတင်အမှတ် : ၁၀၀ ",
      "No products found": "ကုန်ပစ္စည်း မတွေ့ပါ",
      "Intermediate": "အလယ်အလတ်",

      "My Cart": "စျေးခြင်း",
      "Clear   ": "ရှင်းမယ်   ",
      "Item(s) in my cart": "စျေးခြင်းထဲတွင် ရှိသောပစ္စည်းများ",
      "Delete all items": "ပစ္စည်းအားလုံး ဖျက်မယ်",
      "No Products in Cart ": "စျေးခြင်းထဲတွင် မရှိပါ ",
      " + Add Products": " + ပစ္စည်းထည့်မယ်",
      "Retry": "ထပ်မံကြိုးစားမယ်",
      "No subcategories found": "အမျိုးအစားခွဲ မတွေ့ပါ",
      "In Stock": "ပစ္စည်းရှိပါသည်",
      "Dior": "Dior",
      "ChainSaw": "Chainsaw",
      "Box": "လက်ဆောင်ဘူး",
      "Search Product": "ကုန်ပစ္စည်းရှာရန်",

      "No Internet Connection": "အင်တာနက် ချိတ်ဆက်မှု မရှိပါ",
      "Please check your network settings and try again.": "သင့်ကွန်ယက်ဆက်တင်ကို စစ်ဆေးပြီး ထပ်မံကြိုးစားပါ",
      "Cancel": "မလုပ်တော့ပါ",
      "Please upload your payment screenshoot": "သင့်ငွေပေးချေမှု စကရင်ရှော့ကို အပ်လုဒ်လုပ်ပါ",
      "Done": "ပြီးပါပြီ",
      "Enter Full Address": "လိပ်စာအပြည့်အစုံ ရိုက်ထည့်ပါ",
      "Remark": "မှတ်ချက်",
      "Please fill Phone and Password": "ဖုန်းနံပါတ်နှင့် စကားဝှက်ကို ဖြည့်ပါ",
      "Please fill Name": "နာမည်ကို ဖြည့်ပါ",
      "Please fill Phone Number": "ဖုန်းနံပါတ်ကို ဖြည့်ပါ",
      "Please fill Password": "စကားဝှက်ကို ဖြည့်ပါ",
      "Please fill Confirm Password": "စကားဝှက်အတည်ပြုမှုကို ဖြည့်ပါ",
      "Password are not the same": "စကားဝှက် တူညီမှု မရှိပါ",
      "Agree , Term & Conditions": "စည်းကမ်းနှင့် အခြေအန့်များ သဘောတူပါသည်",
      "continue": "ဆက်လက်လုပ်ဆောင်မည်",
      "Did not receive the code": "ကုဒ် မရရှိပါ",
      "Point History": "အမှတ် စာရင်းမှတ်တမ်း",
      "Exchange Products": "ထုတ်ကုန်များ ဖလှယ်ရန်",
      "Your Current Points": "သင့်လက်ရှိ အမှတ်များ",
      "Withdraw Money": "ငွေထုတ်မည်",
      "Enter Point Amount": "အမှတ် အရေအတွက်ထည့်ပါ",
      "Enter Account Number": "အကောင့်နံပါတ် ထည့်ပါ",
      "Enter Account Name": "အကောင့်နာမည် ထည့်ပါ",
      "Point Amount": "အမှတ် အရေအတွက်",
      "Account Number": "အကောင့်နံပါတ်",
      "Account Name": "အကောင့်နာမည်",
      "Add To Cart": "စျေးခြင်းထဲထည့်မည်",
      "Buy Now": "ယခု ဝယ်မည်",
      "Exchange": "ဖလှယ်မည်",
      "Membership": "အသင်းဝင်",
      "Current Points": "လက်ရှိ အမှတ်များ",
      "Profile": "ပရိုဖိုင်",
      "Wishlist": "ဆန္ဒစာရင်း",
      "Privacy Policy": "ကိုယ်ပိုင်အချက်အလက် မူဝါဒ",
      "Delete Account": "အကောင့်ဖျက်မည်",
      "App Setting": "အက်ပ်ဆက်တင်",
      "Language": "ဘာသာစကား",
      "Logout": "ထွက်မည်",
      "Current Points : ": "လက်ရှိ အမှတ်များ : ",
      "Total Earn Points": "စုစုပေါင်း ဝင်ငွေ အမှတ်များ",
      "Withdraw Successful 🎉": "ငွေထုတ်မှု အောင်မြင်ပါသည် 🎉",
      "Account Settings": "အကောင့်ဆက်တင်များ",
    },
  };
}
