// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAx3y6ap8HTE9Tv_XU9oFfM1eb0aXjDvFQ',
    appId: '1:847261512558:web:590735ee1ecc085633077f',
    messagingSenderId: '847261512558',
    projectId: 'sb-jewel',
    authDomain: 'sb-jewel.firebaseapp.com',
    storageBucket: 'sb-jewel.firebasestorage.app',
    measurementId: 'G-XS5BF6E3T9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2L8fTDFbK6OW6rgvmjKLfudyKyCLz8Pg',
    appId: '1:847261512558:android:895146fd7cad0bc333077f',
    messagingSenderId: '847261512558',
    projectId: 'sb-jewel',
    storageBucket: 'sb-jewel.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAv51CLRhnpnoBVCZUVxbhs75bzDk51ukQ',
    appId: '1:847261512558:ios:09fd90570816b01b33077f',
    messagingSenderId: '847261512558',
    projectId: 'sb-jewel',
    storageBucket: 'sb-jewel.firebasestorage.app',
    iosBundleId: 'com.hapeye.spjewellery',
  );

}